[package]
name = "utf"
version = "0.1.0"
edition = "2021"
description = "A UTF code viewer"
license = "MIT"
repository = "https://github.com/okirshen/utf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
